FROM bitnami/redis:7.4

USER root

RUN mkdir /var/log/redis

RUN mkdir /var/lib/data

# COPY ./redis.conf /opt/bitnami/redis//etc/redis.conf
# CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]